version: 0.0.0.{build}
configuration:
  - Debug
  - Release_40
  - Release_45
shallow_clone: true
build:
  project: NETProvider\src\NETProvider.sln
  parallel: true
  verbosity: minimal
before_test:
  - ps: $sourceDir = Resolve-Path .
  - ps: $testsDir = "$sourceDir\NETProvider\src\FirebirdSql.Data.UnitTests\bin\$env:Configuration"
  - ps: mkdir C:\firebird | Out-Null ; cd C:\firebird
  - ps: Start-FileDownload "https://www.dropbox.com/s/y5j3k15gngs8zm1/server.7z?dl=1" | Out-Null
  - ps: 7z x server.7z
  - ps: .\bin\fb_inet_server.exe -a -m
  - ps: cd $testsDir
  - ps: Start-FileDownload "https://www.dropbox.com/s/qcgkjk14bn9h8p7/embedded.7z?dl=1" | Out-Null
  - ps: 7z x embedded.7z
test_script:
  - ps: cd $testsDir
  - ps: nunit-console FirebirdSql.Data.UnitTests.dll /framework:net-4.0 /exclude:Local /nodots /noshadow
artifacts:
  - path: NETProvider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\FirebirdSql.Data.FirebirdClient.dll
  - path: NETProvider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\FirebirdSql.Data.FirebirdClient.pdb
  - path: NETProvider\src\EntityFramework.Firebird\bin\$(Configuration)\EntityFramework.Firebird.dll
  - path: NETProvider\src\EntityFramework.Firebird\bin\$(Configuration)\EntityFramework.Firebird.pdb