version: '{build}'
image: Visual Studio 2017
configuration:
  - Release
environment:
  matrix:
  - name: FB 3.0 (Default)
    fb_download: https://www.dropbox.com/s/x46uy7e5zrtsnux/fb30.7z?dl=1
    fb_start: .\firebird.exe -a

  - name: FB 2.5 (SC)
    fb_download: https://www.dropbox.com/s/ayzjnxjx20vb7s5/fb25.7z?dl=1
    fb_start: .\bin\fb_inet_server.exe -a -m

#  - name: FB 2.5 (CS)
#    fb_download: https://www.dropbox.com/s/ayzjnxjx20vb7s5/fb25.7z?dl=1
#    fb_start: .\bin\fb_inet_server.exe -a
shallow_clone: true
test: off
before_build:
  - ps: nuget restore Provider\src\NETProvider.sln
build:
  project: Provider\src\NETProvider.sln
  parallel: true
  verbosity: minimal
before_test:
  - ps: $sourceDir = Resolve-Path .
  - ps: $testsBaseDir = "$sourceDir\Provider\src\FirebirdSql.Data.UnitTests"
  - ps: $testsNETDir = "$testsBaseDir\bin\$env:Configuration\net452"
  - ps: $testsCOREDir = "$testsBaseDir\bin\$env:Configuration\netcoreapp2.0"

  - ps: mkdir C:\firebird | Out-Null
  - ps: cd C:\firebird
  - ps: Start-FileDownload "$env:fb_download" | Out-Null
  - ps: 7z x ($env:fb_download -replace '.+/([^/]+)\?dl=1','$1')
  - ps: cp -Recurse .\embedded\* $testsNETDir
  - ps: cp -Recurse .\embedded\* $testsCOREDir
  - ps: rmdir -Recurse .\embedded
  - ps: mv .\server\* .
  - ps: rmdir .\server

  - ps: iex $env:fb_start
  - ps: ni firebird.log -ItemType File | Out-Null
test_script:
  - ps: cd $testsNETDir
  - ps: nunit3-console FirebirdSql.Data.UnitTests.dll --framework=net-4.5 --result='NET_results.xml;format=AppVeyor'
                       
  - ps: cd $testsBaseDir
  - ps: $resultsCORE = "$testsCOREDir\CORE_results.xml"
  - ps: dotnet test FirebirdSql.Data.UnitTests.csproj -c $env:Configuration -f netcoreapp2.0 --no-build --no-restore --logger="trx;LogFileName=$resultsCORE"
  - ps: $wc = New-Object System.Net.WebClient
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$env:APPVEYOR_JOB_ID", $resultsCORE)
artifacts:
  - path: Provider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\net452\FirebirdSql.Data.FirebirdClient.dll
  - path: Provider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\net452\FirebirdSql.Data.FirebirdClient.pdb
  - path: Provider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\netstandard1.6\FirebirdSql.Data.FirebirdClient.dll
  - path: Provider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\netstandard1.6\FirebirdSql.Data.FirebirdClient.pdb
  - path: Provider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\netstandard2.0\FirebirdSql.Data.FirebirdClient.dll
  - path: Provider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\netstandard2.0\FirebirdSql.Data.FirebirdClient.pdb
  - path: Provider\src\EntityFramework.Firebird\bin\$(Configuration)\net452\EntityFramework.Firebird.dll
  - path: Provider\src\EntityFramework.Firebird\bin\$(Configuration)\net452\EntityFramework.Firebird.pdb
