version: 0.0.0.{build}
configuration:
  - Debug
  - Release_40
  - Release_45
shallow_clone: true
build:
  project: NETProvider\src\NETProvider.sln
  parallel: true
  verbosity: minimal
before_test:
  - ps: $sourceDir = Resolve-Path .
  - ps: $testsDir = "$sourceDir\NETProvider\src\FirebirdSql.Data.UnitTests\bin\$env:Configuration"
  - ps: mkdir C:\firebird | Out-Null ; cd C:\firebird
  - ps: Start-FileDownload "http://downloads.sourceforge.net/project/firebird/firebird-win32/2.5.5-Release/Firebird-2.5.5.26952-0_Win32.zip" | Out-Null
  - ps: 7z x Firebird-2.5.5.26952-0_Win32.zip
  - ps: sc -Value $null -Path firebird.log -Encoding Ascii
  - ps: .\bin\fb_inet_server.exe -a -m
  - ps: cd $testsDir
  - ps: Start-FileDownload "http://downloads.sourceforge.net/project/firebird/firebird-win64/2.5.5-Release/Firebird-2.5.5.26952-0_x64_embed.zip" | Out-Null
  - ps: 7z x Firebird-2.5.5.26952-0_x64_embed.zip
test_script:
  - ps: cd $testsDir
  - ps: nunit-console FirebirdSql.Data.UnitTests.dll /framework:net-4.0 /exclude:Local /nodots /noshadow
artifacts:
  - path: NETProvider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\FirebirdSql.Data.FirebirdClient.dll
  - path: NETProvider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\FirebirdSql.Data.FirebirdClient.pdb
  - path: NETProvider\src\EntityFramework.Firebird\bin\$(Configuration)\EntityFramework.Firebird.dll
  - path: NETProvider\src\EntityFramework.Firebird\bin\$(Configuration)\EntityFramework.Firebird.pdb