version: 0.0.0.{build}
configuration:
  - Debug
  - Release_40
  - Release_45
shallow_clone: true
build:
  project: NETProvider\src\NETProvider.sln
  parallel: true
  verbosity: minimal
before_test:
  - ps: $sourceDir = Resolve-Path .
  - ps: $testsDir = "$sourceDir\NETProvider\src\FirebirdSql.Data.UnitTests\bin\$env:Configuration"
  - ps: mkdir C:\firebird25 | Out-Null ; cd C:\firebird25
  - ps: Start-FileDownload "https://www.dropbox.com/s/y5j3k15gngs8zm1/server.7z?dl=1" | Out-Null
  - ps: 7z x server.7z
  - ps: .\bin\fb_inet_server.exe -a -m
  - ps: mkdir $testsDir\..\fb25 | Out-Null ; cd $testsDir\..\fb25
  - ps: Start-FileDownload "https://www.dropbox.com/s/qcgkjk14bn9h8p7/embedded.7z?dl=1" | Out-Null
  - ps: 7z x embedded.7z
  - ps: mkdir $testsDir\..\fb3 | Out-Null ; cd $testsDir\..\fb3
  - ps: Start-FileDownload "http://downloads.sourceforge.net/project/firebird/firebird-win64/3.0-Beta_2/Firebird-3.0.0.31896-0_x64_Beta2.zip" | Out-Null
  - ps: 7z x Firebird-3.0.0.31896-0_x64_Beta2.zip
  - ps: copy $sourceDir\firebird3.conf $testsDir\..\fb3\firebird.conf
  - ps: .\firebird.exe -a -m -p 3051
test_script:
  - ps: cd $testsDir
  - ps: nunit3-console FirebirdSql.Data.UnitTests.dll --framework=net-4.0 --where="cat != Local"
artifacts:
  - path: NETProvider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\FirebirdSql.Data.FirebirdClient.dll
  - path: NETProvider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\FirebirdSql.Data.FirebirdClient.pdb
  - path: NETProvider\src\EntityFramework.Firebird\bin\$(Configuration)\EntityFramework.Firebird.dll
  - path: NETProvider\src\EntityFramework.Firebird\bin\$(Configuration)\EntityFramework.Firebird.pdb