version: '0.0.0.{build}'
image: Visual Studio 2017
configuration:
  - Release
environment:
  matrix:
  - name: FB 3.0 (Default)
    fb_download: https://www.dropbox.com/s/x46uy7e5zrtsnux/fb30.7z?dl=1
    fb_start: .\firebird.exe -a

  - name: FB 2.5 (SC)
    fb_download: https://www.dropbox.com/s/ayzjnxjx20vb7s5/fb25.7z?dl=1
    fb_start: .\bin\fb_inet_server.exe -a -m

#  - name: FB 2.5 (CS)
#    fb_download: https://www.dropbox.com/s/ayzjnxjx20vb7s5/fb25.7z?dl=1
#    fb_start: .\bin\fb_inet_server.exe -a
shallow_clone: true
test: off
before_build:
  - ps: $baseDir = Resolve-Path .
build_script:
  - ps: nuget restore $baseDir\Provider\src\NETProvider.sln
  - ps: $baseDir\Provider\build.ps1 -Configuration $env:CONFIGURATION -Version $env:APPVEYOR_BUILD_VERSION  
before_test:
  - ps: $testsBaseDir = "$baseDir\Provider\src\FirebirdSql.Data.UnitTests"
  - ps: $testsNETDir = "$testsBaseDir\bin\$env:CONFIGURATION\net452"
  - ps: $testsCOREDir = "$testsBaseDir\bin\$env:CONFIGURATION\netcoreapp2.0"

  - ps: mkdir C:\firebird | Out-Null
  - ps: cd C:\firebird
  - ps: Start-FileDownload "$env:fb_download" | Out-Null
  - ps: 7z x ($env:fb_download -replace '.+/([^/]+)\?dl=1','$1')
  - ps: cp -Recurse .\embedded\* $testsNETDir
  - ps: cp -Recurse .\embedded\* $testsCOREDir
  - ps: rmdir -Recurse .\embedded
  - ps: mv .\server\* .
  - ps: rmdir .\server

  - ps: iex $env:fb_start
  - ps: ni firebird.log -ItemType File | Out-Null
test_script:
  - ps: cd $testsNETDir
  - ps: nunit3-console FirebirdSql.Data.UnitTests.dll --framework=net-4.5 --result='NET_results.xml;format=AppVeyor'
                       
  - ps: cd $testsBaseDir
  - ps: $resultsCORE = "$testsCOREDir\CORE_results.xml"
  - ps: dotnet test FirebirdSql.Data.UnitTests.csproj -c $env:CONFIGURATION -f netcoreapp2.0 --no-build --no-restore --logger="trx;LogFileName=$resultsCORE"
  - ps: $wc = New-Object System.Net.WebClient
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$env:APPVEYOR_JOB_ID", $resultsCORE)
artifacts:
  - path: Provider\out\**
