trigger:
  branches:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'
stages:
- stage:
  variables:
    CONFIGURATION: Release
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  jobs:
  - job:
    pool:
      vmImage: windows-2019
    workspace:
      clean: all
    timeoutInMinutes: 120
    strategy:
      matrix:
        Provider_FB40:
          FIREBIRD_SELECTION: FB40
          TEST_SUITE: Tests-FirebirdClient
        Provider_FB30:
          FIREBIRD_SELECTION: FB30
          TEST_SUITE: Tests-FirebirdClient
        Provider_FB25:
          FIREBIRD_SELECTION: FB25
          TEST_SUITE: Tests-FirebirdClient

        EFCore_FB40:
          FIREBIRD_SELECTION: FB40
          TEST_SUITE: Tests-EFCore
        EFCore_FB30:
          FIREBIRD_SELECTION: FB30
          TEST_SUITE: Tests-EFCore
        EFCore_FB25:
          FIREBIRD_SELECTION: FB25
          TEST_SUITE: Tests-EFCore

        EF6_FB40:
          FIREBIRD_SELECTION: FB40
          TEST_SUITE: Tests-EF6
        EF6_FB30:
          FIREBIRD_SELECTION: FB30
          TEST_SUITE: Tests-EF6
        EF6_FB25:
          FIREBIRD_SELECTION: FB25
          TEST_SUITE: Tests-EF6
    steps:
    - powershell: |
       try {
         $env:build_wix = 'C:\Program Files (x86)\WiX Toolset v3.11\bin'

         .\Provider\build.ps1 -Configuration $env:CONFIGURATION
         exit $LASTEXITCODE
       }
       catch {
         echo $_
         exit 1
       }
      displayName: Build

    - powershell: |
       try {
         $env:tests_firebird_dir = 'C:\firebird'

         .\Provider\tests.ps1 -Configuration $env:CONFIGURATION -FirebirdSelection $env:FIREBIRD_SELECTION -TestSuite $env:TEST_SUITE
         exit $LASTEXITCODE
       }
       catch {
         echo $_
         exit 1
       }
      displayName: Tests

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifacts
      inputs:
        PathtoPublish: '.\\Provider\\out\\'
